### ISSUE TITLE
FR: NixOS package

### ISSUE THREAD

**Issue by addy419** [rharish101/ReGreet#10]
NixOS has supported greetd for a while but lacks "good" looking greeters. Adding ReGreet as a package will be appreciated.
Due to the nature of NixOS, it is sometimes difficult to add a package such as login managers. So, I don't expect this issue to be solved right away, but I'm willing to try. Any external help is appreciated.

**Comment by fufexan** [comment]
I have a nix package working. I was planning on adding it to Nixpkgs but time wasn't on my side lately. I will do it probably later or tomorrow. In the meantime, check it out [here](https://github.com/fufexan/dotfiles/commit/bf99e04ceb3ab01b552feb22ca1221d3431776b3) (also includes greetd integration and other settings).

**Comment by addy419** [comment]
@fufexan Oh thank you. Yes, I will wait for the package but I kinda understand the method now. Also, is it possible to directly run ReGreet with hyprland nixos (HM) module?
My current greetd settings for tuigreet look like this
```nix
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd Hyprland";
        user = "greeter";
        vt = "next";
      };
    };
  };
```

**Comment by fufexan** [comment]
Yes. I use it with Hyprland. You don't need to pass any commands, as ReGreet will find the `hyprland.desktop` session file and show it as an option.

**Comment by fufexan** [comment]
- https://github.com/NixOS/nixpkgs/pull/219252

It'd be great if you could drop a review.

**Comment by addy419** [comment]
Can you tell me how to add this to the greetd service for hyprland hm module?

**Comment by fufexan** [comment]
You do something similar to the commit I linked yesterday. You add ReGreet as either an overlay or just a simple `callPackage`, and use it instead of tuigreet.

**Comment by fufexan** [comment]
Success! ReGreet was merged https://github.com/NixOS/nixpkgs/pull/219252#event-8676749772. The issue can be closed now.

**Comment by rharish101** [comment]
Before I close this issue, I'd like to advertise this as an unofficial package in the README. Could you write down short instructions to install ReGreet on NixOS?

**Comment by fufexan** [comment]
I was told by a few users to also make a NixOS module for it, to facilitate easy configuration. I will do that and let you know when it's ready.

**Comment by addy419** [comment]
@fufexan I wasn't able to run it trough Hyprland, but it worked with cage. It drops me into tty though (or I have to enter the Hyprland command manually). Could be because Hyprland is installed through home manager, idk if there's a workaround for this. Lastly, icons and themes aren't applied even though I made the file in /etc/greetd/regreet.toml, again (only font works), could be because my themes are installed in home manager instead of system config. This is my config for now:

```nix
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.cage}/bin/cage -s -- ${pkgs.greetd.regreet}/bin/regreet";
        #command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd Hyprland";
        user = "greeter";
        #vt = "next";
      };
    };
  };

  environment.etc."greetd/regreet.toml".text = ''
  #background = "/usr/share/backgrounds/greeter.jpg"
  #background_fit = "Contain"

  [GTK]
  # Whether to use the dark theme
  application_prefer_dark_theme = true

  # Cursor theme name
  cursor_theme_name = "Dracula-cursors"

  # Font name and size
  font_name = "Noto Sans Display 16"

  # Icon theme name
  icon_theme_name = "Papirus"

  # GTK theme name
  theme_name = "Dracula"
  '';

  systemd.tmpfiles.rules = [
    "d /var/log/regreet 0755 greeter greeter - -"
    "d /var/cache/regreet 0755 greeter greeter - -"
  ];
```

If you're able to get this working let me know.

**Comment by fufexan** [comment]
I've opened the PR here https://github.com/NixOS/nixpkgs/pull/221075.

**Comment by fufexan** [comment]
The [module PR](https://github.com/NixOS/nixpkgs/pull/221075) was merged today. It should land in `nixos-unstable` in a few days. Status can be tracked [here](https://nixpk.gs/pr-tracker.html?pr=221075).

CC: @rharish101 
Here's something I would write in the readme regarding NixOS. The middle paragraph is optional.

### NixOS

For a minimal config, add `programs.regreet.enable = true;` in your NixOS configuration file.

This line installs ReGreet, sets up systemd tmpfiles for it, enables `services.greetd` and also configures its default session to start ReGreet using `cage`. This should work on most systems.

For users who want to configure more, they can see all the options of the module by searching for `regreet` on https://search.nixos.org/options.
