### ISSUE TITLE
Documentation on how to change the keymap

### ISSUE THREAD

**Issue by krlwlfrt** [rharish101/ReGreet#101]
I'm not sure if this is a ReGreet or a greetd issue, but I suspect it's a ReGreet issue...

If the fingerprint reading fails and it falls back to password, but I had the issue that I could not login using my password either. I didn't think much of it because I misstype it sometimes and the fingerprint reading succeeded afterwards. But this morning I was poking around a little and was trying to type "sway" in the session field and it gave me "swaz" instead. 
So finally I realized, that this is a keymap issue. So I tried to find something in the docs of ReGreet and greetd on changing the keymap but could not find anything in either.

Can you maybe point me to it or tell me how to do it?

**Comment by rharish101** [comment]
You can set it in the Sway config (or the config of the compositor that you use to drive ReGreet), as specified here: https://wiki.archlinux.org/title/Sway#Keymap

**Comment by rharish101** [comment]
My bad, I just realised that this should probably be added to the README.
