### ISSUE TITLE
Changing reboot and poweroff commands using the config file

### ISSUE THREAD

**Issue by Vulldozer** [rharish101/ReGreet#14]
The Reboot and Shutdown buttons do not function on Void Linux because it uses a different command to shutdown and reboot `loginctl reboot` and `loginctl poweroff`

a simple fix is to allow the user to change the command executed by the buttons in the ReGreet config file.

**Comment by Vulldozer** [comment]
> Doesn't void have the `reboot` and `poweroff` binaries as part of the `runit-void` package? I checked the docker image for void, and they are present. Is there any reason why they don't work in ReGreet?

They do indeed exists but require root privileges to run, loginctl can be run as a regular user

**Comment by rharish101** [comment]
Do all Void Linux installations have DBus installed? I chanced upon a crate [`system_shutdown`](https://crates.io/crates/system_shutdown) that tries different methods through DBus to shut down/reboot before trying the `shutdown`/`reboot` binaries.

**Comment by Vulldozer** [comment]
By default DBus is not installed, however the [Void Linux Handbook](https://docs.voidlinux.org/config/session-management.html) tells the user to install and enable DBus for graphical sessions, **anyone installing a graphical wayland greeter like ReGreet has DBus installed and enabled**
