### ISSUE TITLE
Support for clamshell mode laptops?

### ISSUE THREAD

**Issue by AjiBuster499** [rharish101/ReGreet#23]
Hello, when at home I typically use my laptop in clamshell mode, where the laptop itself is closed and I use an external monitor as my primary monitor. I've tried using ReGreet lately, and while I like it, the (unused) laptop screen seems to be set as primary, and so I cannot actually see the login screen.

Would it be possible to add support for such a laptop setup? I have no experience in this kind of application, but I was wondering if it could be as simple as setting a primary screen in settings, or something to that effect?

**Comment by fufexan** [comment]
I think this is up to the underlying compositor to configure. So if you use Sway to run ReGreet, you would have to search how to use Sway in clamshell mode. I suggest looking into [kanshi](https://sr.ht/~emersion/kanshi) for automatic display configuration based on rules you set.

**Comment by rharish101** [comment]
In that case, I'll have to investigate how GTKGreet handles this, since I was under the impression that it's just a simple GTK3 window, similar to ReGreet (which is GTK4).

**Comment by rharish101** [comment]
@AjiBuster499 could you test ReGreet from PR #25? I don't have a proper multi-monitor setup, so I can't fully test this.

**Comment by AjiBuster499** [comment]
Hi, I just tested it. It did not work, the external monitor had the grey "secondary screen" background, and also based on the mouse being limited to just the external monitor, was the only one it recognized. However ReGreet did not show up on either display, and I had to reboot and keep the lid open to log in successfully like without the PR.

However, I think the PR did restrict it to one display like I said, because if I recall correctly, the main branch allows me to move my mouse between both screens, even though ReGreet doesn't appear on either of them.

**Comment by rharish101** [comment]
@AjiBuster499 Could you try the newest commit on #25 and upload the logs (when running ReGreet with `-l debug`)?

**Comment by rharish101** [comment]
@AjiBuster499 Try the latest commit to see if everything works as intended.

**Comment by AjiBuster499** [comment]
It is in dark mode now, so I do believe everything is working.
