### ISSUE TITLE
PAM Authenticate: AUTH_ERROR with correct password

### ISSUE THREAD

**Issue by scotabroad** [rharish101/ReGreet#26]
On both NixOS and Endeavor OS, I have regreet installed and configured to run with Sway. However, upon login, I receive `Login failed: Pam_authenticate: AUTH_ERROR` despite entering my password. On NixOS, I am using the `program.regreetd.enable = true` option, which means I am using version 0.1.0. On Endeavor OS, I ran `paru -S regreet-git` and followed all basic configuration steps in the README to get it working with Sway.

**Comment by rharish101** [comment]
Could you attach logs when running with `-l debug` from both distros?

**Comment by scotabroad** [comment]
Here is the log file from NixOS: [/var/log/regreet/log](https://github.com/rharish101/ReGreet/files/11313087/log.txt)

**Comment by rharish101** [comment]
Everything seems to be alright in the logs. Can you try with gtkgreet and see if you still get auth errors? The only reason I can think of right now is a different keyboard mapping that ReGreet isn't picking up.

**Comment by scotabroad** [comment]
I have tried gtkgreet and it works

**Comment by scotabroad** [comment]
Okay, so it looks like things work if I hit "enter" or "return" after typing my password, but hitting the login button afterwards generates the auth error.

**Comment by rharish101** [comment]
Great, this is reproducible. I'll start working on a fix...
