### ISSUE TITLE
PAM auth Failed on NixOS

### ISSUE THREAD

**Issue by addy419** [rharish101/ReGreet#27]
After updating to the latest NixOS unstable. I am unable to login because PAM authentication failed. Not sure if this is a ReGreet issue or NixOS issue.

**Comment by rharish101** [comment]
Can you try the latest git commit on `main`? If it still doesn't work, please post logs after running with `-l debug`.

**Comment by addy419** [comment]
I recently updated hyprland and the issue was fixed. I have no idea what caused it.
