### ISSUE TITLE
Preview / demo mode & CSS documentation

### ISSUE THREAD

**Issue by takase1121** [rharish101/ReGreet#30]
Since I can't run regreet without greetd, it's hard to run regreet with `GTK_DEBUG=inspector` and poke around to see what can be customized. Adding a demo mode would really help.

I realized that this program needs layer shell. Even if the inspector is started, I cannot interact with it (that's the whole point!). Are there extra documentation on how to theme regreet in CSS?

**Comment by rharish101** [comment]
> Since I can't run regreet without greetd, it's hard to run regreet with GTK_DEBUG=inspector and poke around to see what can be customized. Adding a demo mode would really help.

Good idea, a demo mode would also help in development. I guess I can try to somehow mock greetd in the codebase with the demo mode.

> I realized that this program needs layer shell.

Could you tell me why? Is it because the inspector doesn't work with it, or is it because it would also provide more features?

> Are there extra documentation on how to theme regreet in CSS?

Not really, it's just like any other GTK app. If you want to see the GTK structure, just see [src/gui/templates.rs](https://github.com/rharish101/ReGreet/blob/0.1.1/src/gui/templates.rs). Specifically, these lines: https://github.com/rharish101/ReGreet/blob/0fb424574643919befeaac9017a5e76741ffb3be/src/gui/templates.rs#L32-L221

**Comment by rharish101** [comment]
> Sorry, I didn't meant it like this - regreet would stay on top of the inspector so one can't use it. I assume the demo mode would allow regreet to run as a normal window, so it can be moved around.

Ah, so you mean that the demo mode should "disable" layer shell? Well, ReGreet doesn't use layer shell; it's just a normal window that's fullscreen.

I develop ReGreet on an X11 desktop (although Wayland might also work, but I haven't tested it) by running it through the command line. It spawns a fullscreen window, which I can reduce to a normal window using my window manager. Then I can access the inspector.

The demo mode I'm thinking of should allow one to use all ReGreet features - like showing the list of (dummy) usernames/sessions, enter (dummy) passwords, etc. - without actually contacting greetd.

**Comment by takase1121** [comment]
> Ah, so you mean that the demo mode should "disable" layer shell? Well, ReGreet doesn't use layer shell; it's just a normal window that's fullscreen.

Oh, didn't know!

> I develop ReGreet on an X11 desktop (although Wayland might also work, but I haven't tested it) by running it through the command line. It spawns a fullscreen window, which I can reduce to a normal window using my window manager. Then I can access the inspector.

How do you connect to greetd when running as another user? I've been trying to figure this out.

**Comment by rharish101** [comment]
> How do you connect to greetd when running as another user? I've been trying to figure this out.

I just run ReGreet as the `greeter` user using `sudo`, as follows:
```sh
sudo -Eu greeter regreet
```

The `-E` switch is to allow passing environment variables. Here, it's needed to get the greetd IPC socket.
