### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Mikilio** [rharish101/ReGreet#34]
I am running NixOS with greetd.
I have done a lot of fiddling to start regreet in a sway session started by greetd, because cage is still [unusable](https://github.com/NixOS/nixpkgs/issues/226586) to me.
What I struggled with the most was getting rid of the 25 sec delay of GTK because it's waiting for answers from dbus (xdg-portal-gtk or something). All this is described in the added [Note](https://github.com/rharish101/ReGreet/blob/61d871a0ee5c74230dfef8100d0c9bc75b309203/README.md?plain=1#L147) however the solution described in this link is supposed to work for normal sway sessions it will not work for greetd.

What I figured out is that what is really need was basically to change [command](https://github.com/rharish101/ReGreet/blob/61d871a0ee5c74230dfef8100d0c9bc75b309203/README.md?plain=1#L143) that starts sway to this instead:
```
/path/to/bin/dbus-run-session /path/to/bin/sway --config /path/to/swayConfig
```
Of course paths don't need to be explicit if they are already in PATH.
In the end it doesn't matter if your add stuff to your configuration (that tries to get some envs from dbus) when sway isn't run with dbus to begin with.

In that sense, please verify my solution is indeed the correct thing to do and update the documentation, so no one has to wait for this beautiful software to start ever again.

**Comment by rharish101** [comment]
I tried this on my Arch system, but I didn't see any difference. I can add this to the note, however.

**Comment by Mikilio** [comment]
That is surprising indeed maybe there is an overall better way to achieve this.

Actually I noticed that doing `exec systemctl --user import-environment` at the beginning also works. Maybe it's a thing with NixOS heavy reliance on systemd for environment variables.

**Comment by rharish101** [comment]
Try asking the person maintaining the NixOS package. They might have some insights. As I'm using Arch, I might not be the right guy, although Arch probably uses systemd in a similar way.
