### ISSUE TITLE
How to hide reboot button or clock widget

### ISSUE THREAD

**Issue by aacebedo** [rharish101/ReGreet#37]
Hi, 

Great greeter! I consider switching to it from gtkgreet.

I think there is no way for the moment to remove the clock widget or the reboot buttons right? I was planning to use waybar for that so I checked CSS properties without success.

**Comment by rharish101** [comment]
I don't think you can hide or disable using GTK4. The closest you can probably get is to use `opacity: 0;` to hide it. Note that the buttons still exist, and you can still click on them. They'll just not be visible.
