### ISSUE TITLE
Custom CSS broken?

### ISSUE THREAD

**Issue by scotabroad** [rharish101/ReGreet#38]
I recently updated regreet on NixOS to v1.1.0 from my custom package now that it is finally in the Nix repository, however, it seems my [custom css](https://github.com/scotabroad/nix-configuration/blob/8067637a84d02bdea8e36f6c11188200b25eb833/theme/rose-pine/base/wayland/regreet.css) no longer works.

It appears somewhere between [this commit](https://github.com/rharish101/ReGreet/tree/ccffff87f621d9ea0d3c0f6ca64b361509d1dbc3) and [this later one](https://github.com/rharish101/ReGreet/tree/f8022a03aff145ea531f1d8534aa29282dd3a458), my custom CSS became broken. However, `/src/gui/template.rs` was not modified between these two, so I have no clue why it is not working anymore.

I have tested the two commits and the v1.1.0 version on both NixOS and EndeavourOS, and only on the first one does my custom css actually work.

This is my login screen on EndeavourOS with commit [ccffff87f621d9ea0d3c0f6ca64b361509d1dbc3](https://github.com/rharish101/ReGreet/tree/ccffff87f621d9ea0d3c0f6ca64b361509d1dbc3)
![20230815_16h40m32s_grim](https://github.com/rharish101/ReGreet/assets/65510090/cb72b250-12ec-4a61-9c29-805cf5bab2c3)

And this is my login screen with commit [f8022a03aff145ea531f1d8534aa29282dd3a458](https://github.com/rharish101/ReGreet/tree/f8022a03aff145ea531f1d8534aa29282dd3a458)
![20230815_16h44m39s_grim](https://github.com/rharish101/ReGreet/assets/65510090/325879d2-cf6e-4660-920c-441bd52cc6a1)

**Comment by scotabroad** [comment]
And this is also with the same custom css file

**Comment by rharish101** [comment]
Could you post the CSS file?
