### ISSUE TITLE
Error when shutting down or restarting

### ISSUE THREAD

**Issue by Xenfo** [rharish101/ReGreet#47]
When I restart or shutdown my PC, it hangs for a while with the following message on screen, the shuts down:
```
[CRITICAL] Critical error thrown: XDG_RUNTIME_DIR is not set!
terminate called after throwing an instance of 'std::runtime_error'
  what(): XDG_RUNTIME_DIR is not set!
```

![image](https://github.com/rharish101/ReGreet/assets/46873232/83b2c855-0cd0-4fa7-b190-d8f49d24874f)

**Comment by rharish101** [comment]
Is this happening only when you shutdown or reboot from ReGreet, or when you do this after login? If it's the former, could you post the logs?

**Comment by Xenfo** [comment]
I haven't been using greetd for a while due to gpu issues, I'm starting to use it again now and I'll let you know if it happens again and grab logs.

**Comment by Xenfo** [comment]
It seems to be fine now, so I'll close this issue and reopen if anything goes wrong.
