### ISSUE TITLE
Default environment

### ISSUE THREAD

**Issue by inmaldrerah** [rharish101/ReGreet#48]
I am using the ReGreet NixOS module, and write
```text
Hyprland
```
in `/etc/greetd/environments` (with `environment.etc."greetd/environments".text` in the NixOS configuration). Although I can find this environment as an option on the login screen, it is not set in the session drop down as the default, even if it is the only environment.

Is there a way to set the default environment? GTKGreet uses the first line in `/etc/greetd/environments` as the default, should it also be the case in ReGreet, i.e. is it NixOS specific?

**Comment by rharish101** [comment]
Nope, ReGreet does not use `/etc/greetd/environments`. It scans the environments from `/usr/share/xsessions` and `/usr/share/wayland-sessions` by default, although this might be different in the NixOS module. You might want to contact the NixOS module maintainers, as I don't maintain it.

As for the default environment, ReGreet simply uses the last environment that you logged into.

**Comment by inmaldrerah** [comment]
Aha, that explains everyting. I am using tmpfs-as-root on NixOS, so on every boot / is created anew, and thus the "last environment" info cannot be saved across reboot on my setup. May I ask to which file the "last environment" info is saved? In this way I can set that file to be preserved across reboot.

**Comment by rharish101** [comment]
Yup, it's `/var/cache/regreet/cache.toml` by default (although the NixOS module might've changed this).
