### ISSUE TITLE
User selection popup shows system users

### ISSUE THREAD

**Issue by fufexan** [rharish101/ReGreet#5]
After ReGreet started, I wanted to select my user from the drop-down list. There were system users listed (0-999 UID), but not my user.
Can the drop-down only include real users (UID 1000+), or have a list of users that can authenticate in the configuration?

**Comment by rharish101** [comment]
Can you share the logs when running ReGreet in debug mode? You can run it as follows:
```sh
regreet -l debug
```

Also, can you check what are values of UID_MIN and UID_MAX in the file `/etc/login.defs`?

**Comment by fufexan** [comment]
[log.txt](https://github.com/rharish101/ReGreet/files/10833489/log.txt)

The values in `/etc/login.defs` say this:
```
UID_MIN      1000
UID_MAX      29999
```

**Comment by rharish101** [comment]
Interesting, the values in `/etc/login.defs` as reported by you are 1000 and 29999, but the logs say that ReGreet finds 400 and 999. Is ReGreet somehow being given the wrong file when it tries to read `/etc/login.defs`? You said that you run NixOS in a comment on another issue, so is ReGreet somehow seeing a different `/etc`? I'm not familiar with NixOS.

**Comment by fufexan** [comment]
Not that I know of. I haven't applied any patches, and it does not go through any mechanism that would override that file.

**Comment by rharish101** [comment]
Can you try this patch out? I fixed the regex:
```
diff --git a/src/sysutil.rs b/src/sysutil.rs
index 19677f3..316389b 100644
--- a/src/sysutil.rs
+++ b/src/sysutil.rs
@@ -56,8 +56,8 @@ impl SysUtil {
 
         // UID_MIN/MAX are limits to a UID for a regular user i.e. a user created with `useradd`.
         // Thus, to find regular users, we filter the list of users with these UID limits.
-        let min_uid_regex = Regex::new(r"UID_MIN\s+([0-9]+)").expect("Invalid regex for UID_MIN");
-        let max_uid_regex = Regex::new(r"UID_MAX\s+([0-9]+)").expect("Invalid regex for UID_MAX");
+        let min_uid_regex = Regex::new(r"^UID_MIN\s+([0-9]+)").expect("Invalid regex for UID_MIN");
+        let max_uid_regex = Regex::new(r"^UID_MAX\s+([0-9]+)").expect("Invalid regex for UID_MAX");
 
         // Get UID_MIN.
         let min_uid = if let Some(num) = min_uid_regex
```

**Comment by fufexan** [comment]
Okay that's a bit better. My user shows up, but also many system users above the `UID_MAX`. Judging from the log, the regex either isn't working as it should or ReGreet can't access `/etc/login.defs`. Here's the  [log.txt](https://github.com/rharish101/ReGreet/files/10833942/log.txt).

Does ReGreet not follow symlinks when accessing files? `/etc/login.defs` is a symlink to `/etc/static/login.defs`, which itself is a symlink to a file in the `/nix/store`, which has permissions 444.

**Comment by rharish101** [comment]
That's weird. Can you post the contents of `/etc/login.defs`, if it doesn't have any confidential info?

**Comment by fufexan** [comment]
Sure, here it is:
```
DEFAULT_HOME yes

SYS_UID_MIN  400
SYS_UID_MAX  999
UID_MIN      1000
UID_MAX      29999

SYS_GID_MIN  400
SYS_GID_MAX  999
GID_MIN      1000
GID_MAX      29999

TTYGROUP     tty
TTYPERM      0620

# Ensure privacy for newly created home directories.
UMASK        077

# Uncomment this and install chfn SUID to allow non-root
# users to change their account GECOS information.
# This should be made configurable.
#CHFN_RESTRICT frwh
```

**Comment by rharish101** [comment]
> Does ReGreet not follow symlinks when accessing files?

It does. If not, a different error would've been thrown.

I fixed the regex. I made the erroneous assumption that Rust's regex engine works line-by-line. Can you test this patch? It works for me on the file you sent:
```diff
diff --git a/src/sysutil.rs b/src/sysutil.rs
index 19677f3..d460fac 100644
--- a/src/sysutil.rs
+++ b/src/sysutil.rs
@@ -56,8 +56,8 @@ impl SysUtil {
 
         // UID_MIN/MAX are limits to a UID for a regular user i.e. a user created with `useradd`.
         // Thus, to find regular users, we filter the list of users with these UID limits.
-        let min_uid_regex = Regex::new(r"UID_MIN\s+([0-9]+)").expect("Invalid regex for UID_MIN");
-        let max_uid_regex = Regex::new(r"UID_MAX\s+([0-9]+)").expect("Invalid regex for UID_MAX");
+        let min_uid_regex = Regex::new(r"\nUID_MIN\s+([0-9]+)").expect("Invalid regex for UID_MIN");
+        let max_uid_regex = Regex::new(r"\nUID_MAX\s+([0-9]+)").expect("Invalid regex for UID_MAX");
 
         // Get UID_MIN.
         let min_uid = if let Some(num) = min_uid_regex
```

**Comment by fufexan** [comment]
Confirming, that fixed it. Sorry I took so long to reply.

**Comment by rharish101** [comment]
Great, I've pushed the fix.
