### ISSUE TITLE
Set window size option

### ISSUE THREAD

**Issue by Vosjedev** [rharish101/ReGreet#50]
Hi!
I would like to have an option to set the window size either in the config or as commandline argument.
Being able to set the window location when that wayland protocol arrives would be nice as well.

This is because I am using tinywl as compositor for regreet. It opens regreet as window on my laptop, which is smaller, but regreet is sized to the size of my external monitor. So I tried without any background image. That made the window small, but smaller than the 'popup' for user and session. I had to resize it to see the total thing.

I will try to make some screenshots and attach those in a moment.

tinywl didn't support screenshots, but I took 2 photos with my phone. Here they are:
![20231117_152250](https://github.com/rharish101/ReGreet/assets/100359465/d5db40e6-5c7c-41a2-ac63-3e89e182355c)
(No background: window to small)
![20231117_152508](https://github.com/rharish101/ReGreet/assets/100359465/609c870c-0493-4a68-81b4-cf7f89bee56c)
(with background: window to big)

**Comment by rharish101** [comment]
That is weird, since ReGreet should be full-screened on a single monitor. Are there any gotchas for tinywl regarding full-screen or multi-monitor support?

**Comment by Vosjedev** [comment]
Tinywl is a very basic implementation usil wl-roots, maybe it does not support fullscreen hints? The reason I am using tinywl is because it is tiny, and it puts regreet in a window. I like to drag my loginscreen around :D .

**Comment by rharish101** [comment]
Could you try gtkgreet and see if it goes into full-screen?

**Comment by Vosjedev** [comment]
Yes I will do so later, but I currently have a lot of stuff open so I need to organise that first before being able to play with greeters again.

**Comment by YaroKasear** [comment]
Unless I'm mistaken, tinywl was never meant for serious usage but just to teach people how to program a compositor.

**Comment by Vosjedev** [comment]
I know, but I want my login screen to be as small as possible, and as cage and regreet doesn't work nicely with multimonitor, I thought a small compositor with windows was better.

**Comment by max-ishere** [comment]
https://man.archlinux.org/man/extra/cage/cage.1.en#ENVIRONMENT

There's `WAYLAND_DISPLAY` that you can use to tell cage what display to use. Idk how consistent the value is and where it comes from tho...

Have you tried it?

**Comment by max-ishere** [comment]
And also there's `cage -mlast` but imo it's pretty annoying

**Comment by Vosjedev** [comment]
Oh, I'll try it. Maybe that can bring back a login screen for me... regreet was broken for me recently (using the `tinywl-git` AUR package gave problems, as expected :D), so I tried qtgreet which wouldn't even start, so now I'm manually starting my WM from the tty.

**Comment by max-ishere** [comment]
Cool. I use these cage args: `-dsmlast`, the -s is for VT switching, I think VT are the tty1,2,3... And I dont feel like getting locked out if cage or regreet does something stupid.

**Comment by Vosjedev** [comment]
> getting locked out

Me neither :D

It at least provided a login screen, thanks! Although I'd still like to do stuff some other way, but I guess having the login screen how I imagined it when setting this system up is going to be harder.

**Comment by max-ishere** [comment]
Can you describe what you expect a bit more?
> I know, but I want my login screen to be as small as possible

Is this referring to window size or amount of code? If security is a concern, cage is a good option because it's purpose is to be used as a kiosk, like on a self-checkout machine. Its minimal and secure.

As for widow size, you can use a black image to mimic the small window look. I haven't tested it yet, but I think if you don't use an image the background will probably be gtk background color. A custom color as a background can be PR'd in if you want.

**Comment by Vosjedev** [comment]
Sorry for the really late response, I haven't gone though my notifications in a while.

> Is this referring to window size or amount of code?
Window size.

> you can use a black image to mimic the small window look
Basically my goal was to have a background image and be able to drag the greeter around as a normal window would behave in a floating window manager. I now solved this by forcing the window to behave how I want using Hyprland with a few window rules as compositor.

Thanks!
If this should be closed now feel free to do so. I'm (as usual) not sure.

**Comment by max-ishere** [comment]
Well, with cage there is another option - spanning over all the monitors. Theoretically what we could do is add a special config section that would support the span mode[^1].

Consider this layout (defined by cage, I don't think there's a way to influence it in any way: not the order, not the position). The regreet window would span the bounding box of all the monitors.

```
       1920    1080
     +-------+-----+
1080 |   1   |  2  | 720
     |       |-----+
     +-------+XXXXXX
_____________________________
XXX - not visible to the user
```

The config could specify a list of "virtual" monitors like this:

```toml
[[cage.span_areas]]
w = 1920
h = 1080
x = 0
y = 0

[[cage.span_areas]]
w = 1080
h = 720
x = 1920
y = 0
```

Then regreet would have to be started in cage mode (cmd flags/config/both). It would then duplicate the background image over all the monitors (or each vmonitor could have it's own background, details don't really matter). Then whatever area is hovered over shows the UI.

I am not sure how to implement this though... Is it really possible? This would definitely require some wild trickery but I think it should be doable with enough dedication.

[^1]: [`man cage.1#OPTIONS`](https://man.archlinux.org/man/cage.1#OPTIONS)

**Comment by rharish101** [comment]
> If this should be closed now feel free to do so. I'm (as usual) not sure.

I'll close the issue now, since OP (@Vosjedev) asked so.
