### ISSUE TITLE
Background image not showing

### ISSUE THREAD

**Issue by thore** [rharish101/ReGreet#51]
I have tried to set the path variable in the [background] to various images, both jpg and png, but to no avail - I only get a solid coloured background. Are there any requirements to this image? Should I try some override with a custom css? I use Arch, btw.

**Comment by thore** [comment]
Custom CSS does not seem to load either. Tried with cage and labwc. Single display.

**Comment by thore** [comment]
So sorry. Forgot to check the permissions of the greeter user. That was embarassing.

**Comment by dante-e-v** [comment]
@thore How did you fix the permissions? While I'm not new to permissions the only thing I can think of would be to either add the "greeter" user to my wheel group which doesn't seem good. Although if it's fine let me know.

**Comment by TurtleMeds** [comment]
i fixed this by putting my wallpapers in a directory in /usr/share as shown in the example configuration. if the wallpaper is in your user's folder, the greeter user will not have access to it for security reasons.
