### ISSUE TITLE
Background image is set to "fit" mode

### ISSUE THREAD

**Issue by fufexan** [rharish101/ReGreet#6]
Currently, an image with an aspect ratio different than the screen will be shrinked to fit, instead of filling the screen. Can we have an option that controls this behaviour?

**Comment by rharish101** [comment]
You can now set it with `background_fit = "..."` in the config file. Please refer to the [comment in the sample config](https://github.com/rharish101/ReGreet/blob/94aad06ef46be06765e6d9fd938df7edafcb5a04/regreet.sample.toml#L8-L11) to see what you can do.
