### ISSUE TITLE
Launching Xorg / X11 window managers

### ISSUE THREAD

**Issue by Akhil-CM** [rharish101/ReGreet#65]
I mentioned this [here](https://github.com/rharish101/ReGreet/issues/15#issuecomment-2028095072) which is an issue thread discussing issues when launching Xorg from X sessions.

I want to know what is the current status?

I will repeat my comment here again:

> I wish to run [herbstluftwm](https://github.com/herbstluftwm/herbstluftwm) with ReGreet. I am using Arch Linux. The desktop entry for herbstluftwm shows the following:
> ```bash
> ~$ cat /usr/share/xsessions/herbstluftwm.desktop
> [Desktop Entry]
> Encoding=UTF-8
> Name=herbstluftwm
> Comment=Manual tiling window manager
> Exec=herbstluftwm --locked
> Type=Application
> ```

> It seems like [tuigreet](https://github.com/apognu/tuigreet/tree/master) does something to properly run X11 sessions. See their `--xsession-wrapper` flag

Right now I am using SDDM login manager.

**Comment by rharish101** [comment]
I don't think anything has changed. If I have more clarity on how I can get ReGreet to start X11 when launching X11 WMs, I would update #16 and merge it. For now, let's keep all discussions in #15 instead of creating duplicates.

**Comment by rharish101** [comment]
Update: I've made changes to #16. If you can test that one out, then it would be great!
