### ISSUE TITLE
Session list is empty

### ISSUE THREAD

**Issue by fufexan** [rharish101/ReGreet#7]
The list is empty and unclickable, so I'm assuming it's not being read properly, as the `/etc/greetd/environments` file gets picked up by gtkgreet. Typing one manually works.

**Comment by rharish101** [comment]
Can you share the logs when running ReGreet in debug mode? You can run it as follows:
```sh
regreet -l debug
```

Also, please check if the directories `/usr/share/xsession` and/or `/usr/share/wayland-sessions`:
- exist
- have read permissions for everyone
- have session files with:
  - a .desktop extension
  - have read permissions for everyone

**Comment by fufexan** [comment]
[log.txt](https://github.com/rharish101/ReGreet/files/10833492/log.txt)

`/usr/share/{xsession,wayland-sessions}` are inaccessible on NixOS because it does not conform to the File Hierarchy Standard. They are not usually set globally, and instead they seem to be exported as `XDG_DATA_DIRS` for some display managers. I guess I could patch ReGreet for Nix to include a different directory instead of `/usr/share`, where I can instruct NixOS to place all the session files.

**Comment by rharish101** [comment]
Ah, in that case, you can probably set the session directories during compile time to the locations given by `XDG_DATA_DIRS` using the `SESSION_DIRS` environment variable. That way, it should be able to read those directories.

**Comment by fufexan** [comment]
Okay, I've set the `SESSION_DIRS` environment variable, which contains `/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share`
```
› l -T /nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share
dr-xr-xr-x   - root  1 Jan  1970  /nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share
dr-xr-xr-x   - root  1 Jan  1970 ├──  wayland-sessions
lrwxrwxrwx 123 root  1 Jan  1970 │  └──  hyprland.desktop -> /nix/store/1bajrcrc7c4dbilirqpppxlf9yi1vk07-hyprland-0.22.0+date=2023-02-26_e302724/share/wayland-sessions/hyprland.desktop
dr-xr-xr-x   - root  1 Jan  1970 └──  xsessions
```

Is this the wrong structure, or is this symlink-related?

**Comment by rharish101** [comment]
Nah, you need to set `SESSION_DIRS=/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share/xsessions:/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share/wayland-sessions`. That environment variable is basically a list of directory paths that are separated by a colon (:). Each directory in that list should contain session desktop files as immediate children, not in subdirectories.

Also, the latest commit fixes an issue with this environment variable (there was a typo in the name of `SESSION_DIRS`). Could you compile the latest code with the correct environment variable?

**Comment by fufexan** [comment]
I have set `SESSION_DIRS=/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share/wayland-sessions:/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share/xsessions` but it still did not show any sessions. Using latest commit.

**Comment by rharish101** [comment]
That's odd. You are setting this environment variable during compilation, right? Because it has no effect at runtime. Compile it as follows:
```sh
SESSION_DIRS=/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share/wayland-sessions:/nix/store/10dxp0sjzg5psr0i521xjsqjrg7w4f1w-desktops/share/xsessions cargo build --release
```

And simply run it as usual.

**Comment by fufexan** [comment]
Oh, I thought it's a runtime variable. I clearly can't read. Wouldn't it be possible to check it at runtime instead? I wouldn't like to need users to recompile the entire dependency tree each time they add/remove/change a session. That's just how rust compilation in nixpkgs is being done, with no cached dependencies, sadly.

**Comment by rharish101** [comment]
Wait, so that directory can change? If yes, then yeah, adding it as a runtime variable makes sense. I'm just gonna need more info about the behaviour before I add support:
- Is it stored in an environment variable, like `XDG_DATA_DIRS`?
- Is the directory structure the same? As in, does the equivalent of `/usr/share` contain the `xsession` and `wayland-sessions` directories, each if which have the session desktop files?
- Do the answers to the above questions hold across distros?

**Comment by fufexan** [comment]
> * Is it stored in an environment variable, like `XDG_DATA_DIRS`?

If you're talking about the session dirs, then yes, for some display managers currently in nixpkgs.

> * Is the directory structure the same? As in, does the equivalent of `/usr/share` contain the `xsession` and `wayland-sessions` directories, each if which have the session desktop files?

Yes.

> * Do the answers to the above questions hold across distros?

At least the environment variable part should hold true for everything. The directory structure management is up to the distro to manage.

In the meantime I've found a way to make it work. Set `SESSION_DIRS=/etc/greetd/xsessions:/etc/greetd/wayland-sessions`, and in those directories I linked the appropriate `/nix/store` paths. It now finally works.

**Comment by rharish101** [comment]
Thanks for your answers. I'm thinking of doing the following:
- Keep the `SESSION_DIRS` behaviour as-is (i.e. only during compile time).
- Check `XDG_DATA_DIRS` at runtime and use it if it exists.
- If it doesn't, then fall back to `SESSION_DIRS` that was set during compile time.

Would this work for you without any workarounds?

**Comment by fufexan** [comment]
Yes, that is ideal. Thank you!
