### ISSUE TITLE
Having to install it twice for it to work.

### ISSUE THREAD

**Issue by h4rldev** [rharish101/ReGreet#77]
My regreet wouldn't start at all and said it wasn't installed, even though I specified my regreet to be enabled in nixos, even specifying the package:

```nix
regreet = {
	     enable = true;
	     package = pkgs.greetd.regreet;
	     settings = /regreet.toml;
	   };
```

This unfortunately didn't work, so I had to install it in system packages aswell, which finally made it work.

**Comment by rharish101** [comment]
Sorry, I'm not the one maintaining NixOS support, so you'll have to contact whoever's doing it. Maybe check #10 to see who it is.

**Comment by h4rldev** [comment]
> Sorry, I'm not the one maintaining NixOS support, so you'll have to contact whoever's doing it. Maybe check #10 to see who it is.

Yeah, I just misunderstood the config, ignore this issue haha
