### ISSUE TITLE
NixOS Support

### ISSUE THREAD

**Issue by aspauldingcode** [rharish101/ReGreet#79]
Add support to NixOS by creating a ReGreet NixOS Module.

**Comment by rharish101** [comment]
Sorry, I don't use NixOS, so I can't make one and test it. Although, there seems to be someone else who is working on it, as per #13. Maybe you could contact them.

**Comment by aspauldingcode** [comment]
Actually, looks like there already is one. Nevermind!
https://search.nixos.org/options?channel=24.05&show=programs.regreet.settings&from=0&size=50&sort=relevance&type=packages&query=regreet
