### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by yavko** [rharish101/ReGreet#8]
Being able to add custom css like in gtkgreet would be cool.

**Comment by rharish101** [comment]
I've added support with commit 393fc5c91e85270cdcea2d652907dd03c8b3f845. You can load a custom CSS file now with `-s` or `--style`.

**Comment by fufexan** [comment]
@rharish101 is it possible make ReGreet load the CSS file from a default location like `/etc/greetd/regreet.css`? Or perhaps specify its path in `regreet.toml`?

**Comment by rharish101** [comment]
Yeah, I can make it behave like the config file, i.e. fixed default path that is configurable with a CLI flag.
