### ISSUE TITLE
Regreet segfaults with mesa 24.3.1

### ISSUE THREAD

**Issue by rooiratel** [rharish101/ReGreet#98]
I'm using Arch Linux.

I just updated the mesa package to version 24.3.1

When using this package, I have a black screen after boot. If I revert to the previous version everything works fine

Checking journalctl I see the below:

Dec 07 13:48:00 rooiratel-pc kernel: regreet[1060]: segfault at 0 ip 00007307c563f478 sp 00007ffd973c0450 error 4 in libgallium-24.3.1-arch1.1.so[7307c5618000+1779000] likely on CPU 0 (core 0, socket 0)
Dec 07 13:48:00 rooiratel-pc kernel: Code: 0f 84 fa 00 00 00 41 83 fe 0c 0f 87 f0 00 00 00 48 8d 35 e7 d1 8d 01 44 89 f1 48 63 0c 8e 48 01 f1 3e ff e1 66 0f 1f 44 00 00 <48> 8b 07 8b 40 40 41 89 04 24 66 66 2e 0f 1f 84 00 00 00 00 00 0f
Dec 07 13:48:00 rooiratel-pc systemd-coredump[1089]: Process 1060 (regreet) of user 969 terminated abnormally with signal 11/SEGV, processing...
Dec 07 13:48:00 rooiratel-pc systemd[1]: Started Process Core Dump (PID 1089/UID 0).
Dec 07 13:48:01 rooiratel-pc systemd-coredump[1090]: [🡕] Process 1060 (regreet) of user 969 dumped core.

**Comment by rharish101** [comment]
I tried it on my current Arch system with Mesa 24.3.1, and it works fine for me. Looking at the linked issue, can you try it without the AMDVLK driver (if you have it installed) or by disabling it? Also, can you try the following:
1. Latest git version (https://aur.archlinux.org/packages/greetd-regreet-git) running on the latest Sway
2. Latest gtkgreet running on the latest Sway

**Comment by rooiratel** [comment]
I'm doing a pacman -Syu now for the first time since reverting back to mesa 24.2.7.

Too many packages are changing now to guess what could break/fix it. This includes linux, mesa, wlroots, and regreet itself. They all have new versions. If this works I'll close the issue, but no idea what would have caused it.

**Comment by rooiratel** [comment]
I've just done a pacman -Syu now for the first time since reverting back to mesa 24.2.7.

It is working now after a full system upgrade.

Too many packages changed to guess what could have fixed it. This includes linux, mesa, wlroots, and regreet itself. They all had new versions.

Closing the issue since it is working now.
